### ISSUE TITLE
 Oauth CLIENT_ID and CLIENT_SECRET

### ISSUE THREAD

**Issue by rnjailamba** [sprintly/sprintly-kanban#84]
I get this error when i do 'node server' - 
`child "clientId" fails because ["clientId" is not allowed to be empty]
`
So i decided to mail sprintly to give oauth credentials to me.
But i got this reply 

> Hi Rnjai,
> 
> We currently aren't able to support local development of Kanban. We're sunsetting the feature, so this probably won't happen.
> 
> Betty Bair

**Is there any workaround to this issue??**

**Comment by nicholasserra** [comment]
No, sorry. As we work on our new kanban feature, this code has become more of a reference. Thank you for the interest though :)

**Comment by rnjailamba** [comment]
@nicholasserra I understand that your company doesnt have the time/ resource to spend on this project.
But since the company had decided to open source it, developers who would like to experiment with this project must be told how to use it if they face a problem.

**Comment by rnjailamba** [comment]
@nicholasserra  It is just a one time effort in my opinion to just give a workaround for this issue so that developers can just look at the working of this application.

**Comment by nicholasserra** [comment]
The issue is that there is no workaround. The kanban code is requiring that you provide sprintly oauth client keys that we are not set up to give out. So the repository, as it sits, is just an example application for reference.

**Comment by rnjailamba** [comment]
@nicholasserra  there must be some code within this application that needs the oauth keys. I am asking if we can somehow suppress that so that people without oauth keys can use this open source project on their local machines.This will help tonnes of people and will make my day.

**Comment by rnjailamba** [comment]
Throw back to this blog post - 

https://sprint.ly/blog/kanban-open-source/

> Our hope is that others in the React community will be able to learn from some of the problems we’ve solved. There’s a benefit for us as well! We’ll get help from the React community when they contribute bug fixes or features to our code.

**Comment by rnjailamba** [comment]
Bump @nicholasserra

**Comment by nicholasserra** [comment]
You are free to modify this code to suppress the necessity of the oauth keys.

**Comment by rnjailamba** [comment]
Thanks i got that working somehow.
Could you please help out by telling what how to get API running on https://local.sprint.ly:9000/ ?

**Comment by nicholasserra** [comment]
That comment is for sprintly developers. This is an oauth application that is meant to connect to the sprintly production server to pull data from the API. Since we are not allowing new oauth applications, as stated, it isn't possible to connect to the API. That's why this is now just example code.

**Comment by rnjailamba** [comment]
Oh fine , got it !
I was asking because the page required calls to 
https://local.sprint.ly:9000/api/user/whoami.json and https://local.sprint.ly:9000/api/products.json
![](http://imgur.com/06YlJoA.jpg)

**Comment by rnjailamba** [comment]
Ended up using angular and have got things working.
FTW
